# Generated by Django 6.0.4 on 2026-05-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('icon_name', models.CharField(default='category', max_length=30)),
                ('is_essential', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('MPESA', 'M-Pesa SMS'), ('CASH', 'Manual Cash'), ('BANK', 'Bank')], default='MPESA', max_length=10)),
                ('transaction_type', models.CharField(choices=[('IN', 'Received'), ('OUT', 'Sent')], default='OUT', max_length=3)),
                ('sms_batch', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('recipient', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_pending_categorization', models.BooleanField(default=True)),
            ],
        ),
    ]
