# Generated by Django 6.0.4 on 2026-05-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color_code',
            field=models.CharField(default='#94A3B8', max_length=10),
        ),
    ]
