# Generated by Django 6.0.4 on 2026-05-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0003_category_color_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='_id',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
