# Generated by Django 6.0.4 on 2026-05-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100)),
                ('threshold_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('severity', models.CharField(choices=[('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('POSITIVE', 'Positive')], max_length=10)),
            ],
        ),
    ]
