# Generated by Django 6.0.4 on 2026-05-09 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Engine', '0001_initial'),
        ('Finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulemetadata',
            name='trigger_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finance.category'),
        ),
    ]
